### ISSUE TITLE
Undefined reference with gnustep-2.2 but not with gnustep-1.9 or gcc

### ISSUE THREAD

**Issue by mcarans** [gnustep/libobjc2#357]
I have tried building Oolite using the supported Clang gnustep-2.2. I get just one linker error. This error does not occur when building Oolite with Clang gnustep 1.9 or gcc. 

I have made a cut down example that demonstrates the issue: https://github.com/mcarans/objc_abi2.2_issue. That example builds with Clang gnustep-1.9, so the undefined reference only happens with gnustep-2.2.

The error I get (which occurs on both MinGW64 and Kubuntu) is:
```
/usr/bin/ld: ./obj/HelloWorld.obj/OOCache.m.o: in function `_i_OOCache_DebugGraphViz_generateGraphVizBodyWithRootNamed_':
/home/mcarans/Code/OoliteRelated/objc_abi2.2_issue/OOCache.m:1098:(.text+0xcdf): undefined reference to `__objc_ivar_offset_OOCache.cache.^{OOCacheImpl=^{OOCacheNode}^{OOCacheNode}^{OOCacheNode}I}'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

It may have something to do with these C structs that are used from Objective-C:

```
struct OOCacheImpl
{
	// Splay tree root
	OOCacheNode				*root;
	
	// Ends of age list
	OOCacheNode				*oldest, *youngest;
	
	unsigned				count;
	NSString				*name;
};


struct OOCacheNode
{
	// Payload
	id<OOCacheComparable>	key;
	id						value;
	
	// Splay tree
	OOCacheNode				*leftChild, *rightChild;
	
	// Age list
	OOCacheNode				*younger, *older;
};

```

My guess is that this is a change in the way C structs are handled in different ABIs within libobjc2, so I [closed](https://github.com/gnustep/libs-base/issues/554) the issue I had made in libs-base and opened here instead, but if it isn't related to libobjc2, then please let me know.

**Comment by mcarans** [comment]
> Can you run nm and see if there is any symbol that starts `__objc_ivar_offset_OOCache.cache`?
> 
> It looks as if the method expects an ivar that is a different version of this type, missing the `NSString*` field at the end. Is it possible that you have two different definitions of `struct OOCacheImpl` visible in different compilation units?

Thanks for your reply. I tried this:

```
nm *.o | grep "__objc_ivar_offset_OOCache.cache"
0000000000000000 B __objc_ivar_offset_OOCache.cache.^{OOCacheImpl=}
                 U __objc_ivar_offset_OOCache.cache.^{OOCacheImpl=^{OOCacheNode}^{OOCacheNode}^{OOCacheNode}I}

```

Is this what you mean?

**Comment by davidchisnall** [comment]
Hmm, that’s interesting. The ivar is emitted as a reference to an opaque type but then referenced with the complete type. That’s a slightly awkward case in the ABI and probably an ABI bug.

You can work around it by defining the struct before the ivar. In modern ObjC, the correct way to do this would be to move the private ivar definitions into the `@implementation` and out of the `@interface`. 

That’s not a fix though: if this is a public ivar, the same problem would exist. I will take a look in clang and see if there’s a nice way of emitting a symbol alias for the ivar offset variable so it appears with both names.

**Comment by davidchisnall** [comment]
Hmm, I cat quite tell what’s going on there. Where is isShip defined, and what is the receiver type?

**Comment by mcarans** [comment]
> Hmm, I cat quite tell what’s going on there. Where is isShip defined, and what is the receiver type?

ShipEntity extends OOEntityWithDrawable (https://github.com/OoliteProject/oolite/blob/master/src/Core/Entities/ShipEntity.h#L192):
`@interface ShipEntity: OOEntityWithDrawable <OOSubEntity, OOBeaconEntity>` 

OOEntityWithDrawable extends Entity (https://github.com/OoliteProject/oolite/blob/master/src/Core/Entities/OOEntityWithDrawable.h#L44):
`@interface OOEntityWithDrawable: Entity`

I can see in https://github.com/OoliteProject/oolite/blob/master/src/Core/Entities/Entity.h#L91:

```
@interface Entity: OOWeakRefObject
{
	// the base object for ships/stations/anything actually
	//////////////////////////////////////////////////////
	//
	// @public variables:
	//
	// we forego encapsulation for some variables in order to
	// lose the overheads of Obj-C accessor methods...
	//
@public
	OOUniversalID			universalID;			// used to reference the entity
	
	unsigned				isShip: 1,

```

and later in https://github.com/OoliteProject/oolite/blob/master/src/Core/Entities/Entity.h#L164 

`- (BOOL) isShip;`

Then in https://github.com/OoliteProject/oolite/blob/master/src/Core/Entities/Entity.m#L131-L134: 
```
- (BOOL)isShip
{
	return isShip;
}
```

Does this help?

**Comment by davidchisnall** [comment]
Hmm, that’s interesting. I wonder if we have a bug with bitfield non-fragile ivars. If you delete the `: 1` then does it work? If so, that gives me a place to look.

**Comment by mcarans** [comment]
> Hmm, that’s interesting. I wonder if we have a bug with bitfield non-fragile ivars. If you delete the `: 1` then does it work? If so, that gives me a place to look.

Oh that fixed it. Oolite started up! (Note that  there are a lot of `:1` elsewhere so not sure if something else will fail later) Thanks a lot for your help to date.

**Comment by mcarans** [comment]
@davidchisnall I tried using MSYS2 MinGW64 built in libobjc2 and GNUStep libraries to build Oolite using ABI 2.2, but I got an error when running on Windows:

<img width="415" height="187" alt="Image" src="https://github.com/user-attachments/assets/1ae2df7b-c9bd-48ec-843b-974a9ebd113f" />

(I use ldd to get all the dependencies and copy them into the oolite.app folder so it is using a copy of the MSYS2 package from /mingw64/bin)

Do you know what is the cause of that one or should I make a new ticket here or in libs-base?

**Comment by davidchisnall** [comment]
I'm struggling to create a test case for the second one.  This is what I have:

```objc
#include "stdio.h"
#include "Test.h"
#include "objc/runtime.h"

@interface Bitfield : Test
{
	unsigned  isShip: 1,
	          isStation: 1;
	int y;
}

@end
@implementation Bitfield
- (BOOL)isShip { return isShip; }
- (BOOL)isStation { return isStation; }
- (void)setShip: (BOOL)aValue
{
	isShip = aValue;
}
- (void)setStation: (BOOL)aValue
{
	isStation = aValue;
}
@end


int main(void)
{
	Bitfield *bf = [Bitfield new];
	assert(![bf isShip]);
	assert(![bf isStation]);
	[bf setShip: YES];
	assert([bf isShip]);
	assert(![bf isStation]);
	[bf setStation: YES];
	assert([bf isShip]);
	assert([bf isStation]);
	assert(class_getInstanceSize([Bitfield class]) == class_getInstanceSize([Test class]) + sizeof(unsigned) + sizeof(int));
	assert(ivar_getOffset(class_getInstanceVariable([Bitfield class], "isShip")) == sizeof(Class));
	assert(ivar_getOffset(class_getInstanceVariable([Bitfield class], "isStation")) == sizeof(Class));
}
```

This passes in the runtime's test suite.  Are you able to reduce the one from OOLite to something that we can include?

**Comment by davidchisnall** [comment]
Please can you test #360?

**Comment by mcarans** [comment]
@davidchisnall That fixed it!

**Comment by davidchisnall** [comment]
Thanks for the reports and, especially, the test cases!
