### ISSUE TITLE
libojbc2 is not compatible with robin-map 1.4

### ISSUE THREAD

**Issue by hobbes1069** [gnustep/libobjc2#333]
I was performing test builds of the dependencies of robin-map in Fedora and ran into the following:

```
In file included from /builddir/build/BUILD/libobjc2-2.1-build/libobjc2-2.1/arc.mm:6:
In file included from /builddir/build/BUILD/libobjc2-2.1-build/libobjc2-2.1/third_party/robin-map/include/tsl/robin_map.h:34:
/builddir/build/BUILD/libobjc2-2.1-build/libobjc2-2.1/third_party/robin-map/include/tsl/robin_hash.h:251:13: error: no member named 'launder' in namespace 'std'; did you mean 'rand_r'?
  251 |     return *std::launder(
      |             ^~~~~~~~~~~~
      |             rand_r
/usr/include/stdlib.h:579:12: note: 'rand_r' declared here
  579 | extern int rand_r (unsigned int *__seed) __THROW;
      |            ^
In file included from /builddir/build/BUILD/libobjc2-2.1-build/libobjc2-2.1/arc.mm:6:
In file included from /builddir/build/BUILD/libobjc2-2.1-build/libobjc2-2.1/third_party/robin-map/include/tsl/robin_map.h:34:
/builddir/build/BUILD/libobjc2-2.1-build/libobjc2-2.1/third_party/robin-map/include/tsl/robin_hash.h:257:13: error: no member named 'launder' in namespace 'std'; did you mean 'rand_r'?
  257 |     return *std::launder(
      |             ^~~~~~~~~~~~
      |             rand_r
/usr/include/stdlib.h:579:12: note: 'rand_r' declared here
  579 | extern int rand_r (unsigned int *__seed) __THROW;
      |            ^
In file included from /builddir/build/BUILD/libobjc2-2.1-build/libobjc2-2.1/arc.mm:6:
In file included from /builddir/build/BUILD/libobjc2-2.1-build/libobjc2-2.1/third_party/robin-map/include/tsl/robin_map.h:34:
/builddir/build/BUILD/libobjc2-2.1-build/libobjc2-2.1/third_party/robin-map/include/tsl/robin_hash.h:1020:30: error: no member named 'clamp' in namespace 'std'
 1020 |     m_min_load_factor = std::clamp(ml, float(MINIMUM_MIN_LOAD_FACTOR),
      |                         ~~~~~^
/builddir/build/BUILD/libobjc2-2.1-build/libobjc2-2.1/third_party/robin-map/include/tsl/robin_hash.h:1025:30: error: no member named 'clamp' in namespace 'std'
 1025 |     m_max_load_factor = std::clamp(ml, float(MINIMUM_MAX_LOAD_FACTOR),
      |                         ~~~~~^
/builddir/build/BUILD/libobjc2-2.1-build/libobjc2-2.1/third_party/robin-map/include/tsl/robin_hash.h:252:9: error: cannot initialize a parameter of type 'unsigned int *' with an rvalue of type 'value_type *' (aka 'std::pair<const void *, (anonymous namespace)::WeakRef *> *')
  252 |         reinterpret_cast<value_type*>(std::addressof(m_value)));
```

Full build log here:
https://download.copr.fedorainfracloud.org/results/hobbes1069/OIIO/fedora-rawhide-x86_64/08876506-libobjc2/builder-live.log.gz

**Comment by davidchisnall** [comment]
std::launder was introduced in C++17 and we build in C++17 mode. 

This looks as if there is a problem with your C++ standard library headers?

**Comment by hobbes1069** [comment]
I’ll dig in a little more but these errors don’t happen when I do a simple rebuild against robin-map 1.3.

**Comment by hobbes1069** [comment]
So Fedora Rawhide is on Clang/LLVM 20, but as I mentioned, it builds fine when I do a simple rebuild with robin-map 1.3. 

I'm not the Fedora maintainer for libobjc2 so I'm unsure how this works, but it appears to:
```
# replace bundled robin-map with the system one
mkdir -p third_party/robin-map/include
ln -s %{_includedir}/tsl third_party/robin-map/include/
```

**Comment by davidchisnall** [comment]
Hmm, is that an old version? We moved from censoring robin map to using FetchContent for it if we fail to detect it. If you want to use the installed version, just installing it before building should work.

**Comment by hobbes1069** [comment]
It's 2.1 which still expects the 3rd party folder. I'm not the maintainer so I can't update the version, at least not without permission, but then I have to check all the dependencies in Fedora if there's a SONAME change.

**Comment by davidchisnall** [comment]
It’s backwards compatible, no need to modify any dependencies.

**Comment by hobbes1069** [comment]
That got me a bit further...
```
In file included from /builddir/build/BUILD/libobjc2-2.2.1-build/libobjc2-2.2.1/arc.mm:10:
In file included from /usr/include/tsl/robin_map.h:34:
In file included from /usr/include/tsl/robin_hash.h:27:
In file included from /usr/lib/gcc/x86_64-redhat-linux/15/../../../../include/c++/15/algorithm:63:
In file included from /usr/lib/gcc/x86_64-redhat-linux/15/../../../../include/c++/15/bits/stl_algo.h:71:
/usr/lib/gcc/x86_64-redhat-linux/15/../../../../include/c++/15/cstdlib:83:15: fatal error: 'stdlib.h' file not found
   83 | #include_next <stdlib.h>
      |               ^~~~~~~~~~
1 error generated.
```

**Comment by davidchisnall** [comment]
It sounds like your C and C++ headers are quite broken. Can you add `-v` to the failing clang line and see what is says?

**Comment by hobbes1069** [comment]
Well more precisely this is a Fedora build which uses a chroot where very few packages are installed by default and the others must be explicitly called out as build requirements in the spec file.

I have manually verified the file is present in the chroot so I think it's building up the directory incorrectly.

**Comment by davidchisnall** [comment]
Please can you run the clang compile command in the chroot and see what -v tells you the search paths are? It’s entirely possible that Fedora’s clang packages have broken search paths for system headers.

**Comment by hobbes1069** [comment]
Here's the output:
```bash
# clang -v
clang version 20.1.2 (Fedora 20.1.2-3.fc43)
Target: x86_64-redhat-linux-gnu
Thread model: posix
InstalledDir: /usr/lib64/llvm20/bin
Configuration file: /etc/clang/x86_64-redhat-linux-gnu-clang.cfg
System configuration file directory: /etc/clang/
Found candidate GCC installation: /usr/lib/gcc/x86_64-redhat-linux/15
Selected GCC installation: /usr/lib/gcc/x86_64-redhat-linux/15
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64
```

**Comment by davidchisnall** [comment]
And are the headers installed in the GCC 15 directories that it is searching?

When you post the build failure output, please can you post *all* of it? It’s hard to help with such limited visibility.

**Comment by hobbes1069** [comment]
The above was from a local build so here's one from COPR:
https://download.copr.fedorainfracloud.org/results/hobbes1069/OIIO/fedora-rawhide-x86_64/08898093-libobjc2/builder-live.log.gz

**Comment by davidchisnall** [comment]
That has the same error:

```
/usr/lib/gcc/x86_64-redhat-linux/15/../../../../include/c++/15/cstdlib:83:15: fatal error: 'stdlib.h' file not found
   83 | #include_next <stdlib.h>
      |               ^~~~~~~~~~
1 error generated.
```

This looks as if the C headers are not installed, or the search paths are configured incorrect.y  It appears to be using GNU libstdc++ as the C++ library, and libstdc++ is not able to find the C headers.  Not sure how this can happen.  Does your platform require you to install a package to get C headers?  If you can add `-###` to this compile command:

```sh
/usr/bin/clang++ -DCXA_ALLOCATE_EXCEPTION_SPECIFIER=noexcept -DGNUSTEP -DNO_LEGACY -DOLDABI_COMPAT=1 -DTYPE_DEPENDENT_DISPATCH -D__OBJC_RUNTIME_INTERNAL__=1 -Dobjc_EXPORTS -isystem /usr/include -x objective-c++ -std=gnu++17 -fPIC -Wno-deprecated-objc-isa-usage -Wno-objc-root-class -fobjc-runtime=gnustep-2.0 -MD -MT CMakeFiles/objc.dir/arc.mm.o -MF CMakeFiles/objc.dir/arc.mm.o.d -o CMakeFiles/objc.dir/arc.mm.o -c /builddir/build/BUILD/libobjc2-2.2.1-build/libobjc2-2.2.1/arc.mm
```

Then it should print the invocation.  You can also try adding `-v`, which should print all of the include paths.

**Comment by hobbes1069** [comment]
I filed a bug but have not heard anything yet. The package can't be completely broken without being noticed as quite a few Fedora packages use clang at this point, but something is not right :)

**Comment by hobbes1069** [comment]
Looks like the problem may be with `-isystem /usr/include` working it's way into the flags. The problem has happened on Debian as well:
https://lists.debian.org/debian-glibc/2020/04/msg00023.html
